# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-01 06:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0006_auto_20171120_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='amount',
            field=models.IntegerField(default=100, verbose_name=b'\xe4\xb9\xb0\xe5\x8d\x96\xe6\x95\xb0\xe9\x87\x8f'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='figure',
            field=models.FloatField(verbose_name=b'\xe6\x88\x90\xe4\xba\xa4\xe9\x87\x91\xe9\xa2\x9d'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='genre',
            field=models.BooleanField(default=True, verbose_name=b'\xe4\xb9\xb0\xe5\x8d\x96\xe7\xb1\xbb\xe5\x9e\x8b'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='number',
            field=models.IntegerField(verbose_name=b'\xe8\x82\xa1\xe7\xa5\xa8\xe7\xbc\x96\xe7\xa0\x81'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name=b'\xe4\xba\xa4\xe6\x98\x93\xe6\x97\xb6\xe9\x97\xb4'),
        ),
        migrations.AlterField(
            model_name='hold',
            name='amount',
            field=models.IntegerField(default=100, verbose_name=b'\xe6\x8c\x81\xe6\x9c\x89\xe6\x95\xb0\xe9\x87\x8f'),
        ),
        migrations.AlterField(
            model_name='hold',
            name='number',
            field=models.IntegerField(verbose_name=b'\xe8\x82\xa1\xe7\xa5\xa8\xe7\xbc\x96\xe7\xa0\x81'),
        ),
        migrations.AlterField(
            model_name='link',
            name='callback_url',
            field=models.URLField(verbose_name=b'url\xe5\x9c\xb0\xe5\x9d\x80'),
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(max_length=50, verbose_name=b'\xe6\xa0\x87\xe9\xa2\x98'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='company_name',
            field=models.CharField(max_length=64, verbose_name=b'\xe5\x85\xac\xe5\x8f\xb8\xe5\x90\x8d\xe7\xa7\xb0'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='flow_in',
            field=models.FloatField(verbose_name=b'\xe6\x80\xbb\xe6\xb5\x81\xe5\x85\xa5'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='flow_out',
            field=models.FloatField(verbose_name=b'\xe6\x80\xbb\xe6\xb5\x81\xe5\x87\xba'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='impressum',
            field=models.TextField(verbose_name=b'\xe5\x85\xac\xe5\x8f\xb8\xe4\xbb\x8b\xe7\xbb\x8d'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='number',
            field=models.IntegerField(verbose_name=b'\xe8\x82\xa1\xe7\xa5\xa8\xe7\xbc\x96\xe7\xa0\x81'),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'\xe5\xb9\xb4\xe9\xbe\x84'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[(b'0', b'\xe7\x94\xb7'), (b'1', b'\xe5\xa5\xb3')], max_length=1, verbose_name=b'\xe6\x80\xa7\xe5\x88\xab'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name=b'\xe6\x89\x8b\xe6\x9c\xba\xe5\x8f\xb7\xe7\xa0\x81'),
        ),
        migrations.AlterField(
            model_name='user',
            name='money',
            field=models.FloatField(blank=True, null=True, unique=True, verbose_name=b'\xe8\xb5\x84\xe9\x87\x91'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profession',
            field=models.CharField(max_length=128, verbose_name=b'\xe8\x81\x8c\xe4\xb8\x9a'),
        ),
        migrations.AlterField(
            model_name='user',
            name='qq',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=b'QQ\xe5\x8f\xb7\xe7\xa0\x81'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name='username'),
        ),
    ]
