# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-24 01:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_author_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='names',
        ),
    ]
