# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-26 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_book_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='book',
            field=models.ManyToManyField(to='index.Book'),
        ),
    ]
